enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Remove viewer discretion dialog' 'Disable precise seeking gesture' 'Seekbar tapping' 'Enable slide to seek' 'Copy video URL' 'Restore old video quality menu' 'Remember video quality' 'Miniplayer' 'Theme' 'Restore old seekbar thumbnails' 'Disable suggested video end screen' 'Hide crowdfunding box' 'Hide endscreen cards' 'Disable rolling number animations' 'Disable resuming Shorts on startup' 'Disable player popup panels' 'SponsorBlock' 'Bypass URL redirects' 'Open links externally' 'GmsCore support' 'Spoof video streams' 'Video ads' 'Hide ads'"
exclusive-patches = true

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
included-patches = "'Open links with app chooser'"
