enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "module"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Spoof client' 'GmsCore support' 'Minimized playback' 'Remove tracking query parameter' 'Hide ads' 'Video ads' 'SponsorBlock' 'Restore old seekbar thumbnails' 'Theme' 'Disable player popup panels' 'Hide endscreen cards' 'Disable fullscreen ambient mode' 'Hide crowdfunding box' 'Hide Shorts components' 'Disable suggested video end screen' 'Disable resuming Shorts on startup' 'Restore old video quality menu' 'Remember video quality' 'Seekbar tapping' 'Enable slide to seek'"
exclusive-patches = true

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
