enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "module"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Bypass URL redirects' 'Disable auto captions' 'Disable fullscreen ambient mode' 'Disable player popup panels' 'Disable precise seeking gesture' 'Disable resuming Shorts on startup' 'Disable rolling number animations' 'Disable suggested video end screen' 'Enable slide to seek' 'Hide ads' 'Hide crowdfunding box' 'Hide endscreen cards' 'Remember video quality' 'Restore old seekbar thumbnails' 'Return YouTube Dislike' 'Restore old video quality menu' 'SponsorBlock' 'Seekbar tapping' 'Spoof app version' 'Spoof client' 'Theme' 'Video ads'"
exclusive-patches = true

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
exclusive-patches = "'Disable switching emoji to sticker'"
build-mode = "module"
