logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# config.toml
[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Seekbar tapping' 'Swipe controls' 'Hide ads' 'Hide \"Get YouTube Premium\" advertisements' 'Video ads' 'Old video quality menu' 'Remember video quality' 'Vanced MicroG support' 'Minimized playback' 'Bypass URL redirects' 'Client spoof' 'Hide breaking news shelf' 'Hide watermark' 'Hide crowdfunding box' 'Disable Shorts on startup' 'Theme' 'Disable player popup panels' 'SponsorBlock' 'Premium heading' 'Custom player overlay opacity'"
exclusive-patches = true
build-mode = "both"
