logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Announcements' 'Bypass URL redirects' 'Open links externally' 'Client spoof' 'Minimized playback' 'Vanced MicroG support' 'Remember video quality' 'Old video quality menu' 'Video ads' 'Hide ads' 'Seekbar tapping' 'Premium heading' 'Hide crowdfunding box' 'Hide info cards' 'Hide breaking news shelf' 'Hide endscreen cards' 'Disable Shorts on startup' 'SponsorBlock' 'Theme' 'Disable player popup panels'"
exclusive-patches = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
